server:
  port: 8761

spring:
  application:
    name: discovery-server
  profiles:
    active: dev

---
spring:
  profiles: dev
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
